api = "0.2"

[buildpack]
id = "tech.atls.buildpacks.yarn-install"
version = "0.0.1"
name = "Yarn Install Buildpack"

[metadata]
include_files = ["dist", "bin/build", "bin/detect", "buildpack.toml"]
pre_package = "yarn build"

[[stacks]]
id = "tech.atls.stacks.node"

[[stacks]]
id = "tech.atls.stacks.node-static"

[[stacks]]
id = "tech.atls.stacks.operator"
