name: Setup composite action

inputs:
  NODE_VERSION:
    required: false
    default: '19'
  REF:
    required: false
    default: ''

runs:
  using: composite

  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.REF }}

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.NODE_VERSION }}

    - name: Install
      run: |
        source .env
        export NODE_OPTIONS
        yarn install --inline-builds
