enableGlobalCache: false

packageExtensions:
  '@actions/http-client@*':
    dependencies:
      undici: '*'
  '@actions/github@*':
    dependencies:
      undici: '*'
  'ink-multi-select@*':
    peerDependencies:
      react: '16'
      ink: '3'
  rollup-plugin-analyzer@*:
    dependencies:
      rollup: '2'
  import-sort-style@*:
    dependencies:
      import-sort-parser: '*'
  import-sort-parser-typescript@*:
    dependencies:
      import-sort-parser: '*'
  '@angular-devkit/core@*':
    dependencies:
      chokidar: '*'
  '@babel/register@*':
    dependencies:
      '@babel/core': '*'
  '@jest/test-result@*':
    dependencies:
      jest-haste-map: '*'
      jest-resolve: '*'
  '@octokit/plugin-paginate-rest@*':
    dependencies:
      '@octokit/core': '*'
  '@rollup/pluginutils@*':
    dependencies:
      '@types/estree': '*'
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: '*'
  'ink-autocomplete@*':
    peerDependencies:
      react: '16'
  'json-joy@*':
    dependencies:
      quill-delta: '*'
      rxjs: '*'
  'cosmiconfig-typescript-loader@*':
    dependencies:
      '@types/node': '18'
      typescript: '4.6.4'
  ink@*:
    dependencies:
      '@types/yoga-layout': '*'

yarnPath: .yarn/releases/yarn-remote.cjs
