compressionLevel: mixed

enableGlobalCache: false

defaultSemverRangePrefix: ''

preferReuse: true

packageExtensions:
  '@actions/github@*':
    dependencies:
      undici: '*'
  '@angular-devkit/core@*':
    dependencies:
      chokidar: '*'
  '@babel/register@*':
    dependencies:
      '@babel/core': '*'
  '@jest/test-result@*':
    dependencies:
      jest-haste-map: '*'
      jest-resolve: '*'
  '@octokit/plugin-paginate-rest@*':
    dependencies:
      '@octokit/core': '*'
  '@rollup/pluginutils@*':
    dependencies:
      '@types/estree': '*'
  cosmiconfig-typescript-loader@*:
    dependencies:
      '@types/node': '20'
      typescript: '5.2.2'
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: '*'
  import-sort-parser-typescript@*:
    dependencies:
      import-sort-parser: '*'
  import-sort-style@*:
    dependencies:
      import-sort-parser: '*'
  ink-autocomplete@*:
    peerDependencies:
      react: '16.14.0'
  ink-multi-select@*:
    peerDependencies:
      ink: '3.2.0'
      react: '16.14.0'
  ink@*:
    dependencies:
      '@types/yoga-layout': '*'
  jest-resolve@*:
    dependencies:
      jest-haste-map: '*'
  node-fetch@*:
    dependencies:
      encoding: '*'
  pkg-tests-core@*:
    dependencies:
      '@jest/globals': '*'
      '@yarnpkg/core': '*'
      '@yarnpkg/fslib': '*'
      '@yarnpkg/parsers': '*'
      finalhandler: '*'
      invariant: '*'
      klaw: '*'
      minimatch: '*'
      pem: dexus/pem
      pkg-tests-fixtures: '*'
      semver: '*'
      serve-static: '*'
      super-resolve: '*'
      tar-fs: '*'
      tslib: '*'
      uuid: '*'
  pkg-tests-fixtures@*:
    dependencies:
      '@yarnpkg/fslib': '*'
  rollup-plugin-analyzer@*:
    dependencies:
      rollup: '*'
  webpack@*:
    dependencies:
      json-schema: '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-esm-loader-typescript.cjs
    spec: 'https://github.com/kherock/yarn-plugins/releases/download/v23.2.0/plugin-esm-loader-typescript.js'
  - path: .yarn/plugins/@yarnpkg/plugin-esm-loader-typescript-patch.cjs

pnpEnableEsmLoader: true

yarnPath: .yarn/releases/yarn.cjs
