enableGlobalCache: false

packageExtensions:
  '@actions/http-client@*':
    peerDependencies:
      undici: '*'
  '@actions/github@*':
    peerDependencies:
      undici: '*'

yarnPath: .yarn/releases/yarn-4.0.2.cjs
