name: Tests composite action

inputs:
  GITHUB_TOKEN:
    required: true

runs:
  using: composite

  steps:
    - name: Release
      shell: bash
      run: |
        source .env
        export NODE_OPTIONS
        yarn checks release
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
