name: Release composite action
description: Create GitHub release for changed packages

inputs:
  GITHUB_TOKEN:
    required: true
    description: GitHub token for creating release

runs:
  using: composite

  steps:
    - name: Create release
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      run: |
        source .env
        export NODE_OPTIONS
        yarn workspaces changed foreach -vtpj 2 exec \
        'bash -c "VERSION=$npm_package_version; \ 
        NAME=$npm_package_name; \
        if [ ! -z \"\$VERSION\" ]; then \
          yarn pack; \
          gh release create \"\$NAME-v\$VERSION\" ./package.tgz --title=\$NAME-\$VERSION; \
        fi"'
