api = "0"

[buildpack]
id = "tech.atls.buildpacks.yarn-workspace-start"
version = "0.0.0"
name = "Yarn Workspace Start Buildpack"

[metadata]
include_files = ["dist", "bin/build", "bin/detect", "buildpack.toml"]
pre_package = "yarn build"

[[stacks]]
id = "tech.atls.stacks.node"

[[stacks]]
id = "tech.atls.stacks.node-static"

[[stacks]]
id = "tech.atls.stacks.operator"
