name: Publish composite action

inputs:
  NPM_TOKEN:
    required: true

runs:
  using: composite

  steps:
    - name: List changed workspaces
      shell: bash
      run: |
        source .env
        export NODE_OPTIONS
        yarn workspaces changed list

    - name: Npm Publish
      shell: bash
      run: |
        source .env
        export NODE_OPTIONS
        yarn workspaces changed foreach -vtp --jobs=2 --no-private npm publish --access public
      env:
        YARN_NPM_AUTH_TOKEN: ${{ inputs.NPM_TOKEN }}
