name: Lint and type check composite action

inputs:
  GITHUB_TOKEN:
    required: true

runs:
  using: composite

  steps:
    - name: Lint
      shell: bash
      run: |
        source .env
        export NODE_OPTIONS
        yarn checks lint
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}

    - name: TypeCheck
      shell: bash
      run: |
        source .env
        export NODE_OPTIONS
        yarn checks typecheck
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
