api = "0"

[buildpack]
id = "tech.atls.buildpacks.yarn-static-workspace"
version = "0.0.0"
name = "Yarn Static Workspace Buildpack"

[metadata]
include_files = ["buildpack.toml"]

[[order]]

[[order.group]]
id = "tech.atls.buildpacks.yarn-install"
version = "0.0.0"

[[order.group]]
id = "tech.atls.buildpacks.yarn-workspace-build"
version = "0.0.0"

[[order.group]]
id = "tech.atls.buildpacks.yarn-workspace-serve"
version = "0.0.0"
