name: Checks composite action
description: Run checks

inputs:
  GITHUB_TOKEN:
    required: true
    description: GitHub token

runs:
  using: composite

  steps:
    - name: Checks
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      shell: bash
      run: |
        source .env
        export NODE_OPTIONS
        yarn checks run

    - name: Release
      if: ${{ !cancelled() }}
      shell: bash
      run: |
        source .env
        export NODE_OPTIONS
        yarn checks release
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}

    - name: JSR publish dry run
      if: ${{ !cancelled() }}
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      shell: bash
      run: |
        source .env
        export NODE_OPTIONS
        yarn workspaces changed foreach --verbose --topological --no-private dlx jsr publish --dry-run
