name: Checks composite action
description: Run checks

inputs:
  GITHUB_TOKEN:
    required: true
    description: GitHub token

runs:
  using: composite

  steps:
    - env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      shell: bash
      run: |
        source .env
        export NODE_OPTIONS
        yarn checks run
