name: Publish JSR composite action
description: Publish packages to JSR

inputs:
  GITHUB_TOKEN:
    description: Token for committing
    required: true

runs:
  using: composite

  steps:
    - name: JSR publish
      shell: bash
      run: |
        source .env
        export NODE_OPTIONS
        yarn workspaces changed foreach -vptj 2 --no-private jsr publish
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
