name: Commit composite action
description: Commit changes

inputs:
  GITHUB_TOKEN:
    required: true
    description: Token for committing
  COMMIT_MESSAGE:
    required: false
    description: Commit message
    default: 'chore(common): publish'
  BRANCH:
    required: false
    default: master
    description: Branch to commit to
  PATTERN:
    required: false
    default: '.'
    description: File pattern for adding to commits

runs:
  using: composite

  steps:
    - name: Commit changes
      uses: planetscale/ghcommit-action@v0.1.44
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      with:
        repo: ${{ github.repository }}
        branch: ${{ inputs.BRANCH }}
        commit_message: ${{ inputs.COMMIT_MESSAGE }}
        file_pattern: ${{ inputs.PATTERN }}
