name: Commit composite action
description: Commit changes

inputs:
  GITHUB_TOKEN:
    required: true
    description: Token for committing
  COMMIT_MESSAGE:
    required: false
    description: Commit message
    default: 'chore(common): publish'
  BRANCH:
    required: false
    default: master
    description: Branch to commit to
  PATTERN:
    required: false
    default: '*.json *.md *.yaml *.yml *.lock'
    description: File pattern for adding to commits

runs:
  using: composite

  steps:
    - name: Compose commit message
      shell: bash
      id: commit_message
      run: |
        source .env
        export NODE_OPTIONS
        INITIAL_MESSAGE=$'chore(common): versions\n\n'
        temp_file=$(mktemp)
        yarn workspaces changed foreach exec "echo \"\$npm_package_name:\$npm_package_version \" >> $temp_file"
        MESSAGE=$(cat $temp_file)
        echo $(cat $temp_file)
        INITIAL_MESSAGE+=$MESSAGE
        INITIAL_MESSAGE="${INITIAL_MESSAGE//'%'/' '}"
        INITIAL_MESSAGE="${INITIAL_MESSAGE//$'\n'/' '}"
        INITIAL_MESSAGE="${INITIAL_MESSAGE//$'\r'/' '}"
        echo "commitMessage=$INITIAL_MESSAGE" >> $GITHUB_OUTPUT
        echo $INITIAL_MESSAGE
        rm $temp_file

    - name: Stage all files
      shell: bash
      run: |
        git add .

    - name: Commit changes
      id: commit
      uses: planetscale/ghcommit-action@v0.2.0
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      with:
        repo: ${{ github.repository }}
        branch: ${{ inputs.BRANCH }}
        commit_message: ${{ steps.commit_message.outputs.commitMessage }}
        file_pattern: ${{ inputs.PATTERN }}
