name: Commit composite action
description: Commit changes

inputs:
  GITHUB_TOKEN:
    required: true
    description: Token for committing
  COMMIT_MESSAGE:
    required: false
    description: Commit message
    default: 'chore(common): publish'
  BRANCH:
    required: false
    default: master
    description: Branch to commit to
  PATTERN:
    required: false
    default: '.'
    description: File pattern for adding to commits

runs:
  using: composite

  steps:
    - name: Get GitHub App User ID
      id: get-user-id
      run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> $GITHUB_OUTPUT
      env:
        GH_TOKEN: ${{ inputs.GITHUB_TOKEN }}

    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      with:
        author_name: ${{ steps.get-user-id.outputs.app-slug }}
        author_email: '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com>'
        message: ${{ inputs.COMMIT_MESSAGE }}
        add: ${{ inputs.PATTERN }}
        commit: -S
