name: Publish composite action

inputs:
  GITHUB_TOKEN:
    required: true

runs:
  using: composite

  steps:
    - name: Patch version
      shell: bash
      run: |
        source .env
        export NODE_OPTIONS
        yarn workspaces changed foreach -pvj 2 --exclude . version patch
        yarn workspaces changed foreach -pvj 2 --exclude . changelog generate
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
