name: Publish composite action

inputs:
  GITHUB_TOKEN:
    required: true

runs:
  using: composite

  steps:
    - name: Patch version
      shell: bash
      run: |
        source .env
        export NODE_OPTIONS
        yarn workspaces changed foreach -tpv --no-private version patch -i
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
