name: Changelog composite action

inputs:
  GITHUB_TOKEN:
    required: true

runs:
  using: composite

  steps:
    - name: Generate changelog
      shell: bash
      run: |
        source .env
        export NODE_OPTIONS
        yarn workspaces changed foreach -pvj 2 changelog generate
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
