name: Checks

on:
  pull_request:

jobs:
  check:
    name: Lint, type check
    env:
      NODE_VERSION: '19'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.NODE_VERSION }}

      - uses: ./.github/actions/install

      - name: Lint and type check
        uses: ./.github/actions/lint-typecheck
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Test unit and integration
        uses: ./.github/actions/test
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: ./.github/actions/release
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
