name: Checks

on:
  pull_request:
    paths-ignore:
      - '.github/**'

jobs:
  check:
    name: Lint, type check
    env:
      NODE_VERSION: '19'
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.ATLANTIS_SUPER_BOT_APP_ID }}
          private-key: ${{ secrets.ATLANTIS_SUPER_BOT_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install
        uses: ./.github/actions/install

      - name: Checks
        uses: ./.github/actions/checks
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
