name: Checks

on: [pull_request]

jobs:
  check:
    name: Lint, typecheck
    uses: ./.github/workflows/reusable-checks.yaml
  release:
    name: Release
    uses: ./.github/workflows/reusable-release.yaml
