name: Checks

on:
  pull_request:

jobs:
  check:
    name: Lint, type check
    env:
      NODE_VERSION: '19'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install
        uses: ./.github/actions/install

      - name: Checks
        uses: ./.github/actions/checks
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
