name: Publish

on:
  pull_request:
    types:
      - closed
    branches:
      - master
    paths-ignore:
      - '.github/**'

jobs:
  run:
    name: Publish
    env:
      NODE_VERSION: '22'
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.ATLANTIS_SUPER_BOT_APP_ID }}
          private-key: ${{ secrets.ATLANTIS_SUPER_BOT_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master
          token: ${{ steps.app-token.outputs.token }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install
        uses: ./.github/actions/install

      - name: Version
        uses: ./.github/actions/version
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Changelog
        if: ${{ !cancelled() }}
        uses: ./.github/actions/changelog
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to NPM
        if: ${{ !cancelled() }}
        id: npm
        uses: ./.github/actions/publish-npm
        with:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to JSR
        if: ${{ !cancelled() }}
        id: jsr
        uses: ./.github/actions/publish-jsr
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        if: ${{ !cancelled() }}
        uses: ./.github/actions/release
        with:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}

      - name: Commit changes
        if: ${{ !cancelled() }}
        uses: ./.github/actions/commit
        with:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
