name: Reusable version

on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  run:
    name: Version
    env:
      NODE_VERSION: '19'
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/actions/setup
        with:
          REF: master

      - name: Version
        uses: ./.github/actions/version
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit changes
        uses: ./.github/actions/commit
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
