name: Reusable version

on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  run:
    name: Version
    env:
      NODE_VERSION: '19'
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.ATLANTIS_SUPER_BOT_APP_ID }}
          private-key: ${{ secrets.ATLANTIS_SUPER_BOT_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master
          token: ${{ steps.app-token.outputs.token }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install
        uses: ./.github/actions/install

      - name: Version
        uses: ./.github/actions/version
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit changes
        uses: ./.github/actions/commit
        with:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          COMMIT_MESSAGE: 'chore(common): versions'
